import { Sku } from "../../../types";

export const productsArr: Sku[] = [
  {
    info: "средство для мытья посуды Crystal",
    measureUnits: "ml",
    unitsCount: 450,
    art: "4604049097548",
    manufacturer: "Нэфис",
    brand: "AOS",
    images: ["/images/aos.png"],
    price: 48.76,
    pack: 0,
    categories: ["средство для мытья посуды"],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur repellendus recusandae minima quis, pariatur laboriosam sunt, odio ipsum, labore error amet magni deleniti temporibus quaerat?",
  },
  {
    info: "Экологичное туалетное мыло",
    measureUnits: "g",
    unitsCount: 90,
    art: "460404909754897",
    manufacturer: "BioMio",
    brand: "BIO-SOAP",
    images: ["/images/soap.png"],
    price: 20.5,
    pack: 0,
    categories: ["средство для мытья посуды", "туалетное мыло"],
    description:
      "Dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. ",
  },
  {
    info: "Порошок стиральный Автомат 100 пятен COMPACT",
    measureUnits: "g",
    unitsCount: 1500,
    art: "46040490975485",
    manufacturer: "J&J",
    brand: "BIMAX",
    images: ["/images/bimax.png"],
    price: 248.76,
    pack: 0,
    categories: ["средство для стирки"],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur repellendus recusandae minima quis, pariatur laboriosam sunt, odio ipsum, labore error amet magni deleniti temporibus quaerat?",
  },
  {
    info: " Автoмат Гель СМС жидкое в растворимых капсулах",
    measureUnits: "ml",
    unitsCount: 30,
    art: "4604049097548495",
    manufacturer: "J&J",
    brand: "ARIEL",
    images: ["/images/ariel.png"],
    price: 90.76,
    pack: 15,
    categories: ["средство для стирки"],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur repellendus recusandae minima quis, pariatur laboriosam sunt, odio ipsum, labore error amet magni deleniti temporibus quaerat?",
  },
  {
    measureUnits: "ml",
    unitsCount: 150,
    info: "Hyaluron Expert Replumping",
    art: "46040490973958",
    manufacturer: "L'Oreal Paris",
    pack: 0,
    brand: "L'Oreal Paris",
    images: [
      "https://i.dummyjson.com/data/products/16/1.png",
      "https://i.dummyjson.com/data/products/16/2.webp",
      "https://i.dummyjson.com/data/products/16/3.jpg",
      "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
    ],
    price: 19,
    categories: ["средство для лица", "skincare"],
    description:
      "L'Oreal© Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
  },
  {
    measureUnits: "ml",
    unitsCount: 150,
    info: "Revitalift Derm Intensives",
    art: "46040490973526",
    manufacturer: "L'Oreal Paris",
    pack: 0,
    brand: "L'Oreal Paris",
    images: [
      "https://i.dummyjson.com/data/products/16/4.jpg",
      "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
    ],
    price: 19,
    categories: ["средство для лица", "skincare"],
    description:
      "L'Oreal© Paris Revitalift Derm Intensives formulated with 1.5% Hyaluronic Acid",
  },
  {
    measureUnits: "ml",
    unitsCount: 450,
    manufacturer: "Hemani Tea",
    pack: 0,
    info: "Hyaluronic Acid Serum",
    brand: "Hemani Tea",
    categories: ["средство для лица", "skincare"],
    description:
      "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria",
    art: "174604049097548",
    images: [
      "https://i.dummyjson.com/data/products/17/1.jpg",
      "https://i.dummyjson.com/data/products/17/2.jpg",
      "https://i.dummyjson.com/data/products/17/3.jpg",
      "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
    ],
    price: 12,
    stock: 78,
  },
  {
    measureUnits: "ml",
    unitsCount: 30,
    manufacturer: "Dermive",
    pack: 0,
    info: "Tree Oil Free Moisturizer",
    brand: "Dermive",
    categories: ["skincare"],
    description:
      "Dermive Oil Free Moisturizer with SPF 20 is ,specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    art: "184604049097548",
    images: [
      "https://i.dummyjson.com/data/products/18/1.jpg",
      "https://i.dummyjson.com/data/products/18/2.jpg",
      "https://i.dummyjson.com/data/products/18/3.jpg",
      "https://i.dummyjson.com/data/products/18/4.jpg",
      "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    ],
    price: 40,
    stock: 88,
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "ROREC",
    pack: 0,
    info: "Oil Free Moisturizer",
    brand: "ROREC White Rice",
    categories: ["skincare"],
    description:
      "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
    art: "194604049097548",
    images: [
      "https://i.dummyjson.com/data/products/19/1.jpg",
      "https://i.dummyjson.com/data/products/19/2.jpg",
      "https://i.dummyjson.com/data/products/19/3.png",
      "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
    ],
    price: 46,
    stock: 54,
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Pakistan",
    pack: 0,
    brand: "Fair & Clear",
    categories: ["skincare"],
    description:
      "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
    art: "204604049097548",
    images: [
      "https://i.dummyjson.com/data/products/20/1.jpg",
      "https://i.dummyjson.com/data/products/20/2.jpg",
      "https://i.dummyjson.com/data/products/20/3.jpg",
      "https://i.dummyjson.com/data/products/20/4.jpg",
      "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
    ],
    price: 70,
    stock: 140,
    info: "Freckle Treatment Cream- ",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "L'Oreal Paris",
    pack: 0,
    brand: "Impression of Acqua Di Gio",
    categories: ["fragrances"],
    description:
      "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",

    art: "114604909754897",
    images: [
      "https://i.dummyjson.com/data/products/11/1.jpg",
      "https://i.dummyjson.com/data/products/11/2.jpg",
      "https://i.dummyjson.com/data/products/11/3.jpg",
      "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
    ],
    price: 13,
    stock: 65,
    info: "perfume Oil",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Royal",
    pack: 0,
    brand: "Royal Mirage",
    categories: ["fragrances"],
    description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    art: "8362440212",
    images: [
      "https://i.dummyjson.com/data/products/12/2.jpg",
      "https://i.dummyjson.com/data/products/12/3.png",
      "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
    ],
    price: 40,
    stock: 52,
    info: "Brown Perfume",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Royal",
    pack: 0,
    brand: "Royal Mirage",
    categories: ["fragrances"],
    description: "Royal_Mirage Sport Silver Perfume for Men & Women - 120ml",
    art: "836244021293847",
    images: [
      "https://i.dummyjson.com/data/products/12/3.png",
      "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
    ],
    price: 40,
    stock: 52,
    info: "Silver Perfume",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Fogg",
    pack: 0,
    brand: "Fog Scent Xpressio",
    categories: ["fragrances"],
    description:
      "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
    art: "8362440213",
    images: [
      "https://i.dummyjson.com/data/products/13/1.jpg",
      "https://i.dummyjson.com/data/products/13/2.png",
      "https://i.dummyjson.com/data/products/13/3.jpg",
      "https://i.dummyjson.com/data/products/13/4.jpg",
      "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    ],
    price: 13,
    stock: 61,
    thumbnail: "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    info: "Fog Scent Xpressio Perfume",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Mahal Al Musk",
    pack: 0,
    brand: "Al Munakh",
    categories: ["fragrances"],
    description:
      "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
    art: "8362440214",
    images: [
      "https://i.dummyjson.com/data/products/14/1.jpg",
      "https://i.dummyjson.com/data/products/14/2.jpg",
      "https://i.dummyjson.com/data/products/14/3.jpg",
      "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
    ],
    price: 120,
    stock: 114,
    thumbnail: "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
    info: "Non-Alcoholic Concentrated Perfume Oil",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Al-Rehab",
    pack: 0,
    brand: "Lord - Al-Rehab",
    categories: ["fragrances"],
    description:
      "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
    art: "8362440215",
    images: [
      "https://i.dummyjson.com/data/products/15/1.jpg",
      "https://i.dummyjson.com/data/products/15/3.jpg",
      "https://i.dummyjson.com/data/products/15/4.jpg",
      "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    ],
    price: 30,
    stock: 105,
    info: "Eau De Perfume Spray",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Al-Dirham",
    pack: 0,
    brand: "Lord - Al-Dirham",
    categories: ["fragrances"],
    description:
      "Genuine  Al-Dirham spray perfume from UAE/Saudi Arabia/Yemen High Quality",
    art: "83624402151",
    images: [
      "https://i.dummyjson.com/data/products/15/2.jpg",
      "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    ],
    price: 30,
    stock: 105,
    info: "Eau De Perfume Spray",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Chanel",
    pack: 0,
    brand: "Chanel #5",
    categories: ["fragrances"],
    description: "Genuine Chanel spray perfume from France High Quality",
    art: "83624402153",
    images: [
      "https://i.dummyjson.com/data/products/15/4.jpg",
      "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    ],
    price: 30,
    stock: 105,
    info: "Eau De Perfume Spray",
  },
];
